"""Live Haiku visual diff tests — fixture-based, deterministic.

Each test calls real claude CLI ($0.001/test). Cost cap fixture asserts
≤2 calls per test. Total session cost: ~$0.004.

Fixtures generated by `python tests/live/fixtures/visual_diff/recorder.py`.
PNGs committed as binary. Manual fixture update via re-run + git diff review.
"""
from pathlib import Path

import pytest

from unity_mcp.sampling import SamplingService

FIXTURES = Path(__file__).parent / "fixtures" / "visual_diff"

pytestmark = [pytest.mark.live, pytest.mark.live_haiku, pytest.mark.asyncio]


CASES = [
    # (pair, prompt, must_contain, must_not_contain)
    ("move_pair",      "Did the box position change between these images? Answer YES or NO only.", "YES", "NO"),
    ("identical_pair", "Did anything change between these images? Answer YES or NO only.",         "NO",  "YES"),
    ("color_pair",     "What color is the box in image 2? Answer with one word only.",             "BLUE", None),
    ("som_pair",       "Which numbered box is colored red? Answer with the digit only.",           "2",    None),
]


@pytest.mark.parametrize("pair,prompt,must,must_not", CASES)
async def test_haiku_visual_diff(pair, prompt, must, must_not, visual_verify_enabled, cost_cap):
    s = SamplingService()
    if not s.enabled:
        pytest.skip("UNITY_MCP_VISUAL_VERIFY!=1")

    before = FIXTURES / pair / "before.png"
    after = FIXTURES / pair / "after.png"
    if not before.exists():
        pytest.skip(f"fixture {pair} missing — run recorder.py")

    result = await s.verify_visual_diff(str(before), str(after), prompt)
    assert result, f"Haiku returned None/empty for {pair}"

    upper = result.upper()
    assert must in upper, f"Expected {must!r} in result, got: {result!r}"

    if must_not is not None:
        # Strip the positive token first to avoid double-match in e.g. "YES, NO change"
        residual = upper.replace(must, "")
        assert must_not not in residual, \
            f"Got conflicting answer with both {must!r} and {must_not!r}: {result!r}"
